import { describe, expect, test } from '@rstest/core';
import { emit } from '../../src/core/emit';
import type { RouteInfo, RouteParam } from '../../src/core/types';

const req = (name: string): RouteParam => ({
  name,
  optional: false,
  splat: false,
});
const opt = (name: string): RouteParam => ({
  name,
  optional: true,
  splat: false,
});
const splat: RouteParam = { name: '*', optional: false, splat: true };

const route = (
  literalPath: string,
  params: RouteParam[] = [],
  origin: RouteInfo['origin'] = 'file-system',
): RouteInfo => ({
  literalPath,
  routerPath: literalPath, // routerPath is irrelevant to emit; keep fixtures short
  params,
  entryName: 'index',
  origin,
});

/** The exact single-entry artifact documented in docs/guide/getting-started.md. */
const DOCS_ROUTES: RouteInfo[] = [
  route('/'),
  route('/about'),
  route('/blog'),
  route('/blog/[id]', [req('id')]),
  route('/docs/$', [splat]),
  route('/users/[id$]', [opt('id')]),
];

const DOCS_ARTIFACT = `/* eslint-disable */
/* prettier-ignore */
// AUTO-GENERATED by modernjs-typed-routes. DO NOT EDIT.
// Regenerate: run \`modern dev\`, \`modern build\`, or \`npx modern typegen\`.
export {};
declare module 'modernjs-typed-routes' {
  interface Register {
    routes: {
      '/': { params: {} };
      '/about': { params: {} };
      '/blog': { params: {} };
      '/blog/[id]': { params: { id: string | number } };
      '/docs/$': { params: { '*': string } };
      '/users/[id$]': { params: { id?: string | number } };
    };
  }
}
`;

test('emits the getting-started artifact byte-for-byte', () => {
  expect(emit(DOCS_ROUTES)).toBe(DOCS_ARTIFACT);
});

describe('param rendering', () => {
  const paramsLine = (r: RouteInfo) => {
    const match = emit([r]).match(/'\S+': ({ params: .*? });\n/);
    if (!match) throw new Error('route line not found in emitted output');
    return match[1];
  };

  test('no params', () => {
    expect(paramsLine(route('/about'))).toBe('{ params: {} }');
  });

  test('required param', () => {
    expect(paramsLine(route('/blog/[id]', [req('id')]))).toBe(
      '{ params: { id: string | number } }',
    );
  });

  test('optional param', () => {
    expect(paramsLine(route('/users/[id$]', [opt('id')]))).toBe(
      '{ params: { id?: string | number } }',
    );
  });

  test('splat param uses the quoted "*" key and string value', () => {
    expect(paramsLine(route('/docs/$', [splat]))).toBe(
      "{ params: { '*': string } }",
    );
  });

  test('multiple params in one path keep path order', () => {
    expect(
      paramsLine(route('/a/[x]/b/[y$]/$', [req('x'), opt('y'), splat])),
    ).toBe(
      "{ params: { x: string | number; y?: string | number; '*': string } }",
    );
  });

  test('param names that are not valid identifiers are quoted', () => {
    expect(paramsLine(route('/x/[foo-bar]', [req('foo-bar')]))).toBe(
      "{ params: { 'foo-bar': string | number } }",
    );
  });
});

describe('options', () => {
  test('trailingSlash: true appends / to every key except the root', () => {
    const output = emit(DOCS_ROUTES, { trailingSlash: true });
    expect(output).toContain("'/': { params: {} };");
    expect(output).toContain("'/about/': { params: {} };");
    expect(output).toContain(
      "'/blog/[id]/': { params: { id: string | number } };",
    );
    expect(output).not.toContain("'/about':");
  });

  test('banner lines are appended to the header before export {}', () => {
    const output = emit(DOCS_ROUTES, { banner: '// plugin v1.2.3' });
    expect(output).toContain(
      '// Regenerate: run `modern dev`, `modern build`, or `npx modern typegen`.\n// plugin v1.2.3\nexport {};\n',
    );
  });
});

describe('robustness', () => {
  test('empty route list still emits a valid module', () => {
    const output = emit([]);
    expect(output).toContain('routes: {};');
    expect(output).toContain("declare module 'modernjs-typed-routes'");
    expect(output.endsWith('\n')).toBe(true);
  });

  test('byte determinism: identical input and shuffled input emit the same bytes', () => {
    const once = emit(DOCS_ROUTES);
    expect(emit(DOCS_ROUTES)).toBe(once);
    expect(emit([...DOCS_ROUTES].reverse())).toBe(once);
  });

  test('output uses \\n endings only and ends with exactly one newline', () => {
    const output = emit(DOCS_ROUTES);
    expect(output).not.toContain('\r');
    expect(output.endsWith('\n')).toBe(true);
    expect(output.endsWith('\n\n')).toBe(false);
  });
});
