import { describe, expect, test } from '@rstest/core';
import { generateRouteTypes } from '../../src/core';
import type { RouteNode } from '../../src/core/types';
import { spikeAdminRoutes, spikeIndexRoutes } from './fixtures/spike-trees';
import { indexPage, page, rootLayout } from './helpers/tree';

const singleEntry = (routes: RouteNode[]) => [
  { entryName: 'index', basename: '/', routes },
];

// ---------------------------------------------------------------------------
// Single entry → plain Register.routes (docs/guide/getting-started.md shape)
// ---------------------------------------------------------------------------

test('single entry emits the plain routes shape regardless of entry name', () => {
  const output = generateRouteTypes(singleEntry(spikeIndexRoutes));
  expect(output).toContain('    routes: {\n');
  expect(output).not.toContain('entries:');
  expect(output).toContain(
    "      '/blog/[id]': { params: { id: string | number } };\n",
  );
});

// ---------------------------------------------------------------------------
// Multi-entry → Register.entries map (docs/guide/route-conventions.md, D13)
// ---------------------------------------------------------------------------

const MULTI_ENTRY_ARTIFACT = `/* eslint-disable */
/* prettier-ignore */
// AUTO-GENERATED by modernjs-typed-routes. DO NOT EDIT.
// Regenerate: run \`modern dev\`, \`modern build\`, or \`npx modern typegen\`.
export {};
declare module 'modernjs-typed-routes' {
  interface Register {
    entries: {
      admin: {
        basename: '/admin';
        routes: {
          '/admin': { params: {} };
          '/admin/users/[userId]': { params: { userId: string | number } };
        };
      };
      index: {
        basename: '/';
        routes: {
          '/': { params: {} };
          '/$': { params: { '*': string } };
          '/about': { params: {} };
          '/blog': { params: {} };
          '/blog/[id]': { params: { id: string | number } };
          '/docs/$': { params: { '*': string } };
          '/login': { params: {} };
          '/promo/[code]': { params: { code: string | number } };
          '/user/profile/[id]/edit': { params: { id: string | number } };
          '/users/[id$]': { params: { id?: string | number } };
        };
      };
    };
  }
}
`;

const playgroundEntries = () => [
  { entryName: 'index', basename: '/', routes: spikeIndexRoutes },
  { entryName: 'admin', basename: '/admin', routes: spikeAdminRoutes },
];

describe('multi-entry (D13)', () => {
  test('emits the per-entry isolated shape from the real spike trees, byte-for-byte', () => {
    expect(generateRouteTypes(playgroundEntries())).toBe(MULTI_ENTRY_ARTIFACT);
  });

  test('entries are sorted by entry name regardless of input order', () => {
    const reversed = [...playgroundEntries()].reverse();
    expect(generateRouteTypes(reversed)).toBe(MULTI_ENTRY_ARTIFACT);
  });

  test('the same path in two entries stays isolated — no cross-entry dedupe', () => {
    const shared = (id: string) => [
      rootLayout(`${id}_layout`, `c/${id}/layout`, [
        page(`${id}_about/page`, `c/${id}/about`, 'about'),
      ]),
    ];
    const output = generateRouteTypes([
      { entryName: 'one', basename: '/', routes: shared('one') },
      { entryName: 'two', basename: '/', routes: shared('two') },
    ]);
    expect(output.match(/'\/about'/g)).toHaveLength(2);
  });

  test('trailingSlash applies inside every entry, root of each basename included', () => {
    const output = generateRouteTypes(playgroundEntries(), {
      trailingSlash: true,
    });
    expect(output).toContain("'/admin/': { params: {} };");
    expect(output).toContain("'/blog/[id]/':");
    expect(output).toContain("'/': { params: {} };");
  });
});

// ---------------------------------------------------------------------------
// Hardening
// ---------------------------------------------------------------------------

describe('hardening', () => {
  test('whole-pipeline shuffle stability: shuffled entries AND children emit identical bytes', () => {
    const shuffle = (nodes: RouteNode[]): RouteNode[] =>
      [...nodes]
        .reverse()
        .map((node) =>
          node.children ? { ...node, children: shuffle(node.children) } : node,
        );
    const shuffled = [
      {
        entryName: 'admin',
        basename: '/admin',
        routes: shuffle(spikeAdminRoutes),
      },
      { entryName: 'index', basename: '/', routes: shuffle(spikeIndexRoutes) },
    ];
    expect(generateRouteTypes(shuffled)).toBe(MULTI_ENTRY_ARTIFACT);
  });

  test('unicode segments and non-identifier params are emitted quoted, never mangled', () => {
    const tree = [
      rootLayout('layout', 'c/layout', [
        page('cafe/page', 'c/cafe', 'café/:niño'),
      ]),
    ];
    const output = generateRouteTypes(singleEntry(tree));
    expect(output).toContain(
      "      '/café/[niño]': { params: { 'niño': string | number } };\n",
    );
  });

  test('deep nesting (20 levels) accumulates correctly', () => {
    let node: RouteNode = indexPage('deep/page', 'c/deep/page');
    for (let depth = 20; depth >= 1; depth--) {
      node = {
        type: 'nested',
        routeType: 'layout',
        origin: 'file-system',
        id: `l${depth}`,
        path: `s${depth}`,
        children: [node],
      };
    }
    const output = generateRouteTypes(
      singleEntry([rootLayout('layout', 'c/layout', [node])]),
    );
    const expectedPath = `/${Array.from({ length: 20 }, (_, i) => `s${i + 1}`).join('/')}`;
    expect(output).toContain(`'${expectedPath}'`);
  });

  test('backslashes never appear in output (Windows-safety)', () => {
    expect(generateRouteTypes(playgroundEntries())).not.toContain('\\');
    expect(
      generateRouteTypes(playgroundEntries(), { trailingSlash: true }),
    ).not.toContain('\\');
  });

  test('empty entry list emits a valid empty-routes module', () => {
    const output = generateRouteTypes([]);
    expect(output).toContain('routes: {};');
  });

  test('onWarn is forwarded to normalize (duplicate dedupe note)', () => {
    const warnings: string[] = [];
    const tree = [
      rootLayout('layout', 'c/layout', [
        page('a/page', 'c/a', 'dup'),
        page('b/page', 'c/b', 'dup'),
      ]),
    ];
    generateRouteTypes(singleEntry(tree), { onWarn: (m) => warnings.push(m) });
    expect(warnings).toHaveLength(1);
  });
});
