/* eslint-disable */
/* prettier-ignore */
// AUTO-GENERATED by modernjs-typed-routes. DO NOT EDIT.
// Regenerate: run `modern dev`, `modern build`, or `npx modern typegen`.
export {};
declare module 'modernjs-typed-routes' {
  interface Register {
    entries: {
      admin: {
        basename: '/admin';
        routes: {
          '/admin': { params: {} };
          '/admin/users/[userId]': { params: { userId: string | number } };
        };
      };
      index: {
        basename: '/';
        routes: {
          '/': { params: {} };
          '/$': { params: { '*': string } };
          '/about': { params: {} };
          '/blog': { params: {} };
          '/blog/[id]': { params: { id: string | number } };
          '/docs/$': { params: { '*': string } };
          '/login': { params: {} };
          '/promo/[code]': { params: { code: string | number } };
          '/user/profile/[id]/edit': { params: { id: string | number } };
          '/users/[id$]': { params: { id?: string | number } };
        };
      };
    };
  }
}
