// Mirrors docs/guide/getting-started.md §3 "Generate" — the sample generated
// file. It provides the Register every other snippet compiles against.
/* eslint-disable */
/* prettier-ignore */
// AUTO-GENERATED by modernjs-typed-routes. DO NOT EDIT.
// Regenerate: run `modern dev`, `modern build`, or `npx modern typegen`.
export {};
declare module 'modernjs-typed-routes' {
  interface Register {
    routes: {
      '/': { params: {} };
      '/about': { params: {} };
      '/blog': { params: {} };
      '/blog/[id]': { params: { id: string | number } };
      '/checkout': { params: {} };
      '/docs/$': { params: { '*': string } };
      '/login': { params: {} };
      '/users/[id$]': { params: { id?: string | number } };
    };
  }
}
