import type { GeneratorOptions, RouteInfo, RouteParam } from './types';

const HEADER = [
  '/* eslint-disable */',
  '/* prettier-ignore */',
  '// AUTO-GENERATED by modernjs-typed-routes. DO NOT EDIT.',
  '// Regenerate: run `modern dev`, `modern build`, or `npx modern typegen`.',
];

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const asKey = (name: string): string =>
  IDENTIFIER_RE.test(name) ? name : `'${name}'`;

function renderParam(param: RouteParam): string {
  if (param.splat) return `${asKey(param.name)}: string`;
  return `${asKey(param.name)}${param.optional ? '?' : ''}: string | number`;
}

function renderParams(params: RouteParam[]): string {
  if (params.length === 0) return '{}';
  return `{ ${params.map(renderParam).join('; ')} }`;
}

/**
 * Renders `RouteInfo[]` into the generated `.d.ts` source string — the exact
 * artifact documented in docs/guide/getting-started.md. Pure string building:
 * the template IS the format (2-space indent, `\n` endings, one trailing
 * newline, keys sorted by literal path). Deterministic for any input order.
 */
export function emit(
  routes: RouteInfo[],
  options: Partial<GeneratorOptions> = {},
): string {
  const { trailingSlash = false, banner } = options;

  const keyOf = (route: RouteInfo): string =>
    trailingSlash && route.literalPath !== '/'
      ? `${route.literalPath}/`
      : route.literalPath;

  const sorted = [...routes].sort((a, b) =>
    a.literalPath < b.literalPath ? -1 : a.literalPath > b.literalPath ? 1 : 0,
  );

  const routeLines = sorted.map(
    (route) =>
      `      '${keyOf(route)}': { params: ${renderParams(route.params)} };`,
  );

  const routesBlock =
    routeLines.length === 0
      ? ['    routes: {};']
      : ['    routes: {', ...routeLines, '    };'];

  const lines = [
    ...HEADER,
    ...(banner ? [banner] : []),
    'export {};',
    "declare module 'modernjs-typed-routes' {",
    '  interface Register {',
    ...routesBlock,
    '  }',
    '}',
  ];

  return `${lines.join('\n')}\n`;
}
